// Generated from AnnotExp.g4 by ANTLR 4.5.3
package autogenerated.listener;
import org.antlr.v4.runtime.tree.ParseTreeListener;

/**
 * This interface defines a complete listener for a parse tree produced by
 * {@link AnnotExpParser}.
 */
public interface AnnotExpListener extends ParseTreeListener {
	/**
	 * Enter a parse tree produced by {@link AnnotExpParser#s}.
	 * @param ctx the parse tree
	 */
	void enterS(AnnotExpParser.SContext ctx);
	/**
	 * Exit a parse tree produced by {@link AnnotExpParser#s}.
	 * @param ctx the parse tree
	 */
	void exitS(AnnotExpParser.SContext ctx);
	/**
	 * Enter a parse tree produced by the {@code MulExp}
	 * labeled alternative in {@link AnnotExpParser#e}.
	 * @param ctx the parse tree
	 */
	void enterMulExp(AnnotExpParser.MulExpContext ctx);
	/**
	 * Exit a parse tree produced by the {@code MulExp}
	 * labeled alternative in {@link AnnotExpParser#e}.
	 * @param ctx the parse tree
	 */
	void exitMulExp(AnnotExpParser.MulExpContext ctx);
	/**
	 * Enter a parse tree produced by the {@code AddExp}
	 * labeled alternative in {@link AnnotExpParser#e}.
	 * @param ctx the parse tree
	 */
	void enterAddExp(AnnotExpParser.AddExpContext ctx);
	/**
	 * Exit a parse tree produced by the {@code AddExp}
	 * labeled alternative in {@link AnnotExpParser#e}.
	 * @param ctx the parse tree
	 */
	void exitAddExp(AnnotExpParser.AddExpContext ctx);
	/**
	 * Enter a parse tree produced by the {@code Int}
	 * labeled alternative in {@link AnnotExpParser#e}.
	 * @param ctx the parse tree
	 */
	void enterInt(AnnotExpParser.IntContext ctx);
	/**
	 * Exit a parse tree produced by the {@code Int}
	 * labeled alternative in {@link AnnotExpParser#e}.
	 * @param ctx the parse tree
	 */
	void exitInt(AnnotExpParser.IntContext ctx);
}