// Generated from AnnotExp.g4 by ANTLR 4.5.3
package autogenerated.visitor;
import org.antlr.v4.runtime.tree.ParseTreeVisitor;

/**
 * This interface defines a complete generic visitor for a parse tree produced
 * by {@link AnnotExpParser}.
 *
 * @param <T> The return type of the visit operation. Use {@link Void} for
 * operations with no return type.
 */
public interface AnnotExpVisitor<T> extends ParseTreeVisitor<T> {
	/**
	 * Visit a parse tree produced by {@link AnnotExpParser#s}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitS(AnnotExpParser.SContext ctx);
	/**
	 * Visit a parse tree produced by the {@code MulExp}
	 * labeled alternative in {@link AnnotExpParser#e}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitMulExp(AnnotExpParser.MulExpContext ctx);
	/**
	 * Visit a parse tree produced by the {@code AddExp}
	 * labeled alternative in {@link AnnotExpParser#e}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitAddExp(AnnotExpParser.AddExpContext ctx);
	/**
	 * Visit a parse tree produced by the {@code Int}
	 * labeled alternative in {@link AnnotExpParser#e}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitInt(AnnotExpParser.IntContext ctx);
}