package application;

import java.io.IOException;
import org.antlr.v4.runtime.*;
import org.antlr.v4.runtime.tree.*;

import autogenerated.visitor.AnnotExpLexer;
import autogenerated.visitor.AnnotExpParser;
import walker.AnnotExpExtendVisitor;



public class TreeWalkerApplicationVisitor {
	public static void main(String[] args) throws IOException {
		//Create a CharStream that reads from standard input
		ANTLRInputStream input = ANTLRInputStreamUtils.getStandardInputStream( );
		//Create a lexer that feeds off of input CharStream
		AnnotExpLexer lexer = new AnnotExpLexer(input);
		//Create a buffer of tokens pulled from the lexer
		CommonTokenStream tokens = new CommonTokenStream(lexer);
		//Create a parser that feeds off the tokens buffer
		AnnotExpParser parser = new AnnotExpParser(tokens);
		//Begin parsing at init rule
		ParseTree tree = parser.s( ); 

		//Create the visitor
		AnnotExpExtendVisitor visitor = new AnnotExpExtendVisitor( );
		//Visit the tree created by the parser
		System.out.println(tree.accept(visitor));
	}
}
