# Reproduce the "magic" of the makefiles distributed with pin
# Source: http://www.cs.swarthmore.edu/~bylvisa1/cs97/f13/pin_tutorial.html

##################################################
# IMPORTANT: set PIN_ROOT to the directory where #  
# the pin executable is located in your machine! #
##################################################
#export PIN_ROOT ${HOME}/projects/compilers-cin/pin/pin-2.14-71313-clang.5.1-mac/
CONFIG_ROOT := $(PIN_ROOT)/source/tools/Config

include $(CONFIG_ROOT)/makefile.config
include $(PIN_ROOT)/source/tools/ManualExamples/makefile.rules
include $(TOOLS_ROOT)/Config/makefile.default.rules



