# Reproduce the "magic" of the makefiles distributed with pin
# Source: http://www.cs.swarthmore.edu/~bylvisa1/cs97/f13/pin_tutorial.html

##################################################
# IMPORTANT: set PIN_ROOT to the directory where #  
# the pin executable is located in your machine! #
##################################################
PIN_ROOT := /home/damorim/Tools/pin-2.14-71313-gcc.4.4.7-linux/
CONFIG_ROOT := $(PIN_ROOT)/source/tools/Config

include $(CONFIG_ROOT)/makefile.config
include $(PIN_ROOT)/source/tools/ManualExamples/makefile.rules
include $(TOOLS_ROOT)/Config/makefile.default.rules



