package walker;

import java.util.HashMap;
import java.util.Map;

import autogenerated.TestBaseVisitor;
import autogenerated.TestParser;



public class TestExtendVisitor extends TestBaseVisitor<Integer> {
	Map<String, Integer> simpleSymbolTable = new HashMap<String, Integer>( );
	
	@Override
	public Integer visitAssign(TestParser.AssignContext ctx) {
		//ID is the token at the left of the '='
		String id = ctx.ID( ).getText( ); 
		int value = ctx.expr( ).accept(this);
		
		simpleSymbolTable.put(id, value);
		
		/*  
		 *  We can also get information about the individual tokens
		 *  Token token = (Token) ctx.ID( ).getPayload( );
		 *  int line = token.getLine( );
		 */
		
		return value;
	}
	
	@Override
	public Integer visitAddSub(TestParser.AddSubContext ctx) {
		//Get value of left subexpression
		int left = ctx.expr(0).accept(this); 
		//Get value of right subexpression
		int right = ctx.expr(1).accept(this);  
		int result = 0;

		if (ctx.op.getType( ) == TestParser.ADD) {
			result = left + right;
		} else {
			result = left - right;
		}
		
		return result;
	}
	
	@Override
	public Integer visitInt(TestParser.IntContext ctx) {
		return Integer.valueOf(ctx.INT( ).getText( ));
	}
	
	@Override
	protected Integer aggregateResult(Integer aggregate, Integer nextResult) {
		return (nextResult != null) ? nextResult : aggregate;
	}
	
}
