#!/bin/bash

if [ -z ${CURRDIR} ];
then
    "Variable CURRDIR is not set.  Please check!"
    exit
fi

export SRCDIR=${CURRDIR}/src
export SRCTESTSDIR=${CURRDIR}/src-tests
export BINDIR=${CURRDIR}/bin
export LIBDIR=${CURRDIR}/libs
export DATADIR=${CURRDIR}/dat

CLASSPATH=$BINDIR
for x in `ls $LIBDIR/*.jar`
do
    CLASSPATH=$CLASSPATH:$x
done

OS_KERNEL=`uname -s`
if [ $OS_KERNEL = "Darwin" ]
    then
        DOTPATH="/usr/local/bin/dot"
    else
        DOTPATH="/usr/bin/dot"
fi

export CLASSPATH
export OS_KERNEL