#!/bin/bash

## this is the name of the project directory.
CURRDIR="$(X=`pwd` && find $X -name "common" | sed "s/common//").."

## load variable definitions to help scripts (e.g., CLASSPATH, BINDIR, etc.)
source ${CURRDIR}/scripts/common

## go to the project root
cd $CURRDIR

## run regression tests
java -cp $CLASSPATH org.junit.runner.JUnitCore rwsets.AllTests 

## go back
cd scripts
